### ISSUE TITLE
Integration Tests Periodically fail due to "Recursive Update"

### ISSUE THREAD

**Issue by JasonTypesCodes** [jhipster/generator-jhipster-micronaut#122]
##### **Overview of the issue**

The integration tests are periodically failing due to the following:

```
[ERROR] testCorsFilterDeactivated  Time elapsed: 2.944 s  <<< ERROR!
io.micronaut.context.exceptions.BeanInstantiationException: 
Error instantiating bean of type  [io.micronaut.validation.validator.resolver.CompositeTraversableResolver]

Message: Recursive update
Path Taken: new DefaultValidator([ValidatorConfiguration configuration]) --> DefaultValidatorConfiguration.setTraversableResolver([TraversableResolver traversableResolver]) --> new CompositeTraversableResolver([List traversableResolvers])
	at com.mycompany.myapp.config.CorsTest.testCorsFilterDeactivated(CorsTest.java:56)
Caused by: java.lang.IllegalStateException: Recursive update
	at com.mycompany.myapp.config.CorsTest.testCorsFilterDeactivated(CorsTest.java:56)
```

##### **Reproduce the error**

https://github.com/jhipster/generator-jhipster-micronaut/runs/886184785?check_suite_focus=true

##### **Project configuration**

All of the sample projects seem to periodically have this issue

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by JasonTypesCodes** [comment]
Example project (with client removed for faster builds: https://github.com/JasonTypesCodes/mhipster-recursive-update

**Comment by JasonTypesCodes** [comment]
Micronaut 2.0.1 should be releasing soon and should address this
