### ISSUE TITLE
Contributions instructions out of date?

### ISSUE THREAD

**Issue by agilob** [jhipster/generator-jhipster-micronaut#231]
I needed to update mhipster and jhipster, installation and npm link worked, but I can't generate mhipster application:

```
❯ mhipster
Local install was preferred but not found.
INFO! Using JHipster version installed globally
INFO! No custom sharedOptions found within blueprint: generator-jhipster-micronaut at /usr/lib/node_modules/generator-jhipster-micronaut
INFO! No custom commands found within blueprint: generator-jhipster-micronaut at /usr/lib/node_modules/generator-jhipster-micronaut
INFO! Error parsing options for generator jhipster-micronaut:app, unknown option will lead to error at jhipster 7
     info Using blueprint generator-jhipster-micronaut for app subgenerator
WARNING! Priority composing is missing for generator jhipster-micronaut:app. Merging into default priority.


 ███╗   ███╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
 ████╗ ████║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
 ██╔████╔██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
 ██║╚██╔╝██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
 ██║ ╚═╝ ██║ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
 ╚═╝     ╚═╝ ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech
                              https://micronaut.io

 Welcome to MHipster v0.8.0 :: Running Micronaut v2.3.4
 This blueprint generates your backend as a Micronaut Java project.
 _______________________________________________________________________________________________________________

 :: This project is a Micronaut blueprint for JHipster
 :: Please let us know if you encounter issues
 :: https://github.com/jhipster/generator-jhipster-micronaut/issues
 _______________________________________________________________________________________________________________

  If you find MHipster useful, support and star the project at:
  https://github.com/jhipster/generator-jhipster-micronaut
 _______________________________________________________________________________________________________________

ERROR! The installed generator-jhipster-micronaut blueprint targets JHipster v6.10.5 and is not compatible with this JHipster version. Either update the blueprint or JHipster. You can also disable this check using --skip-checks at your own risk
Error: The installed generator-jhipster-micronaut blueprint targets JHipster v6.10.5 and is not compatible with this JHipster version. Either update the blueprint or JHipster. You can also disable this check using --skip-checks at your own risk
    at module.exports.error (/home/agilob/Projects/generator-jhipster/generators/generator-base.js:1770:11)
    at module.exports._checkJHipsterBlueprintVersion (/home/agilob/Projects/generator-jhipster/generators/generator-base-blueprint.js:397:14)
    at /home/agilob/Projects/generator-jhipster/generators/app/index.js:296:18
    at Array.forEach (<anonymous>)
    at module.exports.validateBlueprint (/home/agilob/Projects/generator-jhipster/generators/app/index.js:295:42)
    at Object.<anonymous> (/home/agilob/Projects/generator-jhipster/node_modules/yeoman-generator/lib/index.js:974:25)
    at /home/agilob/Projects/generator-jhipster/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /home/agilob/Projects/generator-jhipster/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/home/agilob/Projects/generator-jhipster/node_modules/yeoman-generator/lib/index.js:975:11)
    at Immediate.<anonymous> (/home/agilob/Projects/generator-jhipster/node_modules/grouped-queue/lib/subqueue.js:48:34)
    at processImmediate (node:internal/timers:464:21)
```

```
❯ mhipster  --skip-checks
Local install was preferred but not found.
INFO! Using JHipster version installed globally
INFO! No custom sharedOptions found within blueprint: generator-jhipster-micronaut at /usr/lib/node_modules/generator-jhipster-micronaut
INFO! No custom commands found within blueprint: generator-jhipster-micronaut at /usr/lib/node_modules/generator-jhipster-micronaut
INFO! Error parsing options for generator jhipster-micronaut:app, unknown option will lead to error at jhipster 7
     info Using blueprint generator-jhipster-micronaut for app subgenerator
WARNING! Priority composing is missing for generator jhipster-micronaut:app. Merging into default priority.


 ███╗   ███╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
 ████╗ ████║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
 ██╔████╔██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
 ██║╚██╔╝██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
 ██║ ╚═╝ ██║ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
 ╚═╝     ╚═╝ ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech
                              https://micronaut.io

 Welcome to MHipster v0.8.0 :: Running Micronaut v2.3.4
 This blueprint generates your backend as a Micronaut Java project.
 _______________________________________________________________________________________________________________

 :: This project is a Micronaut blueprint for JHipster
 :: Please let us know if you encounter issues
 :: https://github.com/jhipster/generator-jhipster-micronaut/issues
 _______________________________________________________________________________________________________________

  If you find MHipster useful, support and star the project at:
  https://github.com/jhipster/generator-jhipster-micronaut
 _______________________________________________________________________________________________________________

? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? What is the base name of your application? mhip2
ERROR! jhContext.setupServerOptions is not a function
TypeError: jhContext.setupServerOptions is not a function
    at new module.exports (/home/agilob/Projects/generator-jhipster-micronaut/generators/server/index.js:49:19)
    at Environment.instantiate (/home/agilob/Projects/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:747:23)
    at Environment.create (/home/agilob/Projects/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:719:17)
    at module.exports.composeWith (/home/agilob/Projects/generator-jhipster/node_modules/yeoman-generator/lib/index.js:1147:42)
    at module.exports.composeServer (/home/agilob/Projects/generator-jhipster-micronaut/generators/app/index.js:91:22)
    at Object.<anonymous> (/home/agilob/Projects/generator-jhipster/node_modules/yeoman-generator/lib/index.js:974:25)
    at /home/agilob/Projects/generator-jhipster/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /home/agilob/Projects/generator-jhipster/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/home/agilob/Projects/generator-jhipster/node_modules/yeoman-generator/lib/index.js:975:11)
    at Immediate.<anonymous> (/home/agilob/Projects/generator-jhipster/node_modules/grouped-queue/lib/subqueue.js:48:34)
    at processImmediate (node:internal/timers:464:21)
```

Which version should I be using?

**Comment by agilob** [comment]
nvm it says in the error. I just switched jhipster-generator branch to v6.10.5 :D
