### ISSUE TITLE
Getting started instructions fail w/ Error: ENOENT: no such file or directory, scandir 'generator-jhipster/lib/generators'

### ISSUE THREAD

**Issue by isentrope** [jhipster/generator-jhipster-micronaut#270]
##### **Reproduce the error**

➜  src npm --version                                                                   
8.19.3
➜  src ls /usr/local/lib/node_modules/                                           
npm/
➜  src npm install -g generator-jhipster-micronaut

<installs>

➜  src ls /usr/local/lib/node_modules/            
generator-jhipster-micronaut/	npm/
➜  src mkdir jhipster
➜  src cd jhipster/
➜  jhipster mhipster
Local install was preferred but not found.
INFO! Using JHipster version installed globally
INFO! No custom sharedOptions found within blueprint: generator-jhipster-micronaut at /usr/local/lib/node_modules/generator-jhipster-micronaut
INFO! No custom commands found within blueprint: generator-jhipster-micronaut at /usr/local/lib/node_modules/generator-jhipster-micronaut
INFO! Executing jhipster:app
     info Using blueprint generator-jhipster-micronaut for app subgenerator
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/generator-jhipster/lib/generators'
    at Object.readdirSync (node:fs:1444:3)
    at exports.readdir (/usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/@mrmlnc/readdir-enhanced/lib/sync/fs.js:18:20)
    at Object.safeCall [as safe] (/usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:24:8)
    at DirectoryReader.readNextDirectory (/usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:78:10)
    at DirectoryReader.stream._read (/usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:57:18)
    at Readable.read (node:internal/streams/readable:496:12)
    at readdirSync (/usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/@mrmlnc/readdir-enhanced/lib/sync/index.js:27:21)
    at Function.readdirSyncStat (/usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/@mrmlnc/readdir-enhanced/lib/index.js:34:10)
    at ReaderSync.dynamicApi (/usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/fast-glob/out/providers/reader-sync.js:64:24)
    at ReaderSync.api (/usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/fast-glob/out/providers/reader-sync.js:56:25)
Emitted 'error' event on Readable instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/generator-jhipster/lib/generators'
}

Node.js v19.1.0
➜  jhipster 
➜  jhipster mhipster -V  
Local install was preferred but not found.
INFO! Using JHipster version installed globally
INFO! No custom sharedOptions found within blueprint: generator-jhipster-micronaut at /usr/local/lib/node_modules/generator-jhipster-micronaut
INFO! No custom commands found within blueprint: generator-jhipster-micronaut at /usr/local/lib/node_modules/generator-jhipster-micronaut
6.10.5

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by isentrope** [comment]
The failing directory ^^^ indeed does not exist, neither does the lib prefix directory for it.

➜  jhipster ls /usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/generator-jhipster/lib/generators  
ls: /usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/generator-jhipster/lib/generators: No such file or directory
➜  jhipster ls /usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/generator-jhipster/              
LICENSE.txt	NOTICE		README.md	cli/		generators/	node_modules/	package.json	utils/
➜  jhipster ls /usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/generator-jhipster/

**Comment by vhooz** [comment]
same problem here, Node.js v19.6.0

**Comment by mraible** [comment]
This should be fixed in the `main` branch now. You must use Node 18 because that's what JHipster 8 requires. Please re-open if it's not fixed.
